name = "site-worker"
type = "webpack"
workers_dev = false

[site]
bucket = "./out"
entry-point = "workers-site"

[env.production]
name = "site-worker-production"
route = "sidv.dev/*"
vars = { BASE_URL = "https://sidv.dev" } 
